version: 2.1
workflows:
  build:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:19.5.0
      - image: cimg/postgres:10.17
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      NODE_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    steps:
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - checkout
      - run: npm i @prisma/client
      - run: npm i prisma-graphql-type-decimal
      - run: npm i prisma-nestjs-graphql
      - run: sudo npm install -g prisma
      - run: sudo prisma generate
      - run: npm run start test:e2e
      - run: npm run start build

  create-review-app:
    executor: heroku/default
    steps:
      - checkout
      - run:
          command: tar -czvf my-project.tar.gz ~/project
          name: Bundle our project project
          working_directory: ~/
      - store_artifacts:
          path: ~/my-project.tar.gz
      - heroku/create-review:
          artifact-pattern: '*.tar.gz'
          pipeline: PIPELINE-UUID
